### ISSUE TITLE
Python misspelled in the readme <3

### ISSUE THREAD

**Issue by pontussjostedt** [Attrup/zplane#3]

**Comment by ShivamMenda** [comment]
Hey @Attrup Will correct it.

**Comment by ShivamMenda** [comment]
Are there any other issues that I can address so that I can help you out with the project?

**Comment by Attrup** [comment]
@pontussjostedt Good catch! Thanks for letting me know!

**Comment by Attrup** [comment]
@ShivamMenda Thanks for your work! This repo was developed for a university course in Digital Signal Processing and is not something I'm actively developing. As far as I know there are no further issues with the module.
